name: Grade

on:
  workflow_dispatch:
    inputs:
      repo-url:
        description: 'URL of the repository to grade'
        required: true
      callback-url:
        description: 'URL used to send the grading results back'
        required: true
      callback-password:
        description: 'Password to use shen sending back grading results'
        required: true

jobs:
  build:
    name: Grade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '16'
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: ./mvnw package exec:java
        env:
          REPO_URL: ${{ github.event.inputs.repo-url }}
          CALLBACK_URL: ${{ github.event.inputs.callback-url }}
          CALLBACK_PASSWORD: ${{ github.event.inputs.callback-password }}
